title: Karym Metwally's Page

remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

minima:
  social_links:
   - { platform: subscribe, user_url: "https://twitter.com/jekyllrb" }
